/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.SubLineaController;
import VistaDialogos.DialogoLinea;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author eduardo
 */
public class DialogoBusquedaTabla extends javax.swing.JDialog {

    /**
     * Creates new form DialogoTest
     */
    SubLineaController controller;

    public DialogoBusquedaTabla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new SubLineaController(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogLinea = new javax.swing.JDialog();
        txtCodLinea = new javax.swing.JTextField();
        btnAceptarBusqueda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodSublinea = new javax.swing.JTextField();
        btnCancelarBusqueda = new javax.swing.JButton();
        txtDescripcionLinea = new javax.swing.JTextField();
        txtDescripcionSublinea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Tablas ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodLineaKeyReleased(evt);
            }
        });
        getContentPane().add(txtCodLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));

        btnAceptarBusqueda.setText("Aceptar");
        btnAceptarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Linea :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SubLinea :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        txtCodSublinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodSublineaKeyReleased(evt);
            }
        });
        getContentPane().add(txtCodSublinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, -1));

        btnCancelarBusqueda.setText("Cancelar");
        btnCancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 30));
        getContentPane().add(txtDescripcionLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 180, -1));
        getContentPane().add(txtDescripcionSublinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarBusquedaActionPerformed
        // TODO add your handling code here:
        VistaSublinea.txtcodigoSubLinea.setText(txtCodSublinea.getText());
        VistaSublinea.txtDescripcionSubLinea.setText(txtDescripcionSublinea.getText());
        VistaSublinea.seletLinea.setSelectedItem(Utilitarios.Utilitario.getTablaId(Conection.Conexion.conexions(), "saLineaArticulo", "co_lin", "lin_des", txtCodLinea.getText()));
        VistaSublinea.btnEliminar.setEnabled(true);
        VistaSublinea.btnactulizar.setEnabled(true);
        dispose();
    }//GEN-LAST:event_btnAceptarBusquedaActionPerformed

    private void txtCodLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodLineaKeyReleased
        // TODO add your handling code here:
        if (txtCodLinea == evt.getSource()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                DialogoLinea JdialogoLinea = new DialogoLinea(new JFrame(), rootPaneCheckingEnabled);
                JdialogoLinea.setSize(472, 358);
                JdialogoLinea.setLocationRelativeTo(null);
                JdialogoLinea.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtCodLineaKeyReleased

    private void txtCodSublineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodSublineaKeyReleased
        // TODO add your handling code here:
        if (txtCodSublinea == evt.getSource()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                JDialogoBusquedaAsistida busqueda = new JDialogoBusquedaAsistida(new JFrame(), true);
                busqueda.setSize(472, 358);
                busqueda.setLocationRelativeTo(null);
                busqueda.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtCodSublineaKeyReleased

    private void btnCancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusquedaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoBusquedaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoBusquedaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoBusquedaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoBusquedaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoBusquedaTabla dialog = new DialogoBusquedaTabla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarBusqueda;
    private javax.swing.JButton btnCancelarBusqueda;
    private javax.swing.JDialog jDialogLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField txtCodLinea;
    public static javax.swing.JTextField txtCodSublinea;
    public static javax.swing.JTextField txtDescripcionLinea;
    public static javax.swing.JTextField txtDescripcionSublinea;
    // End of variables declaration//GEN-END:variables
}
