/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import VistaDialogos.DialogoBusquedaTabla;
import Beans.SubLineaBO;
import Model.ModeloTablaSubLinea;
import Model.SublineaModel;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo
 */
public class JDialogoBusquedaAsistida extends javax.swing.JDialog {

    /**
     * Creates new form JDialogoBueçsquedaAsistida
     */
    public JDialogoBusquedaAsistida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pObtenerListadoDatosSubLinea("admin_a", "saSubLinea", "subl_des", "", "2", DialogoBusquedaTabla.txtCodLinea.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoBusqueda = new javax.swing.ButtonGroup();
        btnGrupoOpcion = new javax.swing.ButtonGroup();
        jPanel16 = new javax.swing.JPanel();
        jRInicio4 = new javax.swing.JRadioButton();
        jRFinal4 = new javax.swing.JRadioButton();
        jrCualquier4 = new javax.swing.JRadioButton();
        jRexacta4 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        txtBuscarValorSubLinea = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtableSubLinea = new javax.swing.JTable();
        btnAceptarSubLinea = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jrCodigo4 = new javax.swing.JRadioButton();
        jrDescripcion4 = new javax.swing.JRadioButton();
        btnCancelarSubLinea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Asistida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion"));

        btnGrupoOpcion.add(jRInicio4);
        jRInicio4.setText("1) Inicio");
        jRInicio4.setToolTipText("Coincida al inicio");

        btnGrupoOpcion.add(jRFinal4);
        jRFinal4.setText("2)Final");
        jRFinal4.setToolTipText("Coincida al Final");

        btnGrupoOpcion.add(jrCualquier4);
        jrCualquier4.setSelected(true);
        jrCualquier4.setText("3)Cualquier");
        jrCualquier4.setToolTipText("Cualquier Caracter");

        btnGrupoOpcion.add(jRexacta4);
        jRexacta4.setText("4)exacta");
        jRexacta4.setToolTipText("Exacta Caracter");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRFinal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jrCualquier4)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jRInicio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jRexacta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jRInicio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFinal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrCualquier4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRexacta4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 130));

        jLabel28.setText("Buscar :");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        txtBuscarValorSubLinea.setToolTipText("Buscar");
        txtBuscarValorSubLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarValorSubLineaKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarValorSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, -1));

        jtableSubLinea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jtableSubLinea);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 120));

        btnAceptarSubLinea.setText("Aceptar");
        btnAceptarSubLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarSubLineaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptarSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 98, -1));

        jLabel29.setText("Total de Registros Encontrados");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 180, -1));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));

        btnGrupoBusqueda.add(jrCodigo4);
        jrCodigo4.setSelected(true);
        jrCodigo4.setText("Codigo");
        jrCodigo4.setToolTipText("Codigo");

        btnGrupoBusqueda.add(jrDescripcion4);
        jrDescripcion4.setText("Descripcion");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrDescripcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jrCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jrCodigo4)
                .addGap(18, 18, 18)
                .addComponent(jrDescripcion4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 100));

        btnCancelarSubLinea.setText("Cancelar");
        btnCancelarSubLinea.setToolTipText("Cancelar");
        btnCancelarSubLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSubLineaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarValorSubLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarValorSubLineaKeyReleased
        // TODO add your handling code here:
        if (txtBuscarValorSubLinea == evt.getSource()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                String Opcion4 = "0", sfieldName4 = "";
                if (jRInicio4.isSelected()) {
                    Opcion4 = "0";
                } else if (jRFinal4.isSelected()) {
                    Opcion4 = "1";
                } else if (jrCualquier4.isSelected()) {
                    Opcion4 = "2";
                } else if (jRexacta4.isSelected()) {
                    Opcion4 = "3";
                }
                sfieldName4 = (jrCodigo4.isSelected()) ? "co_subl" : "subl_des";
                pObtenerListadoDatosSubLinea("admin_a", "saSubLinea", sfieldName4, txtBuscarValorSubLinea.getText(), Opcion4, DialogoBusquedaTabla.txtCodLinea.getText());
            }
        }
    }//GEN-LAST:event_txtBuscarValorSubLineaKeyReleased

    private void btnCancelarSubLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSubLineaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarSubLineaActionPerformed

    private void btnAceptarSubLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarSubLineaActionPerformed
        // TODO add your handling code here:
        int selection = jtableSubLinea.getSelectedRow();
        if (selection != -1) {
            DialogoBusquedaTabla.txtCodSublinea.setText(jtableSubLinea.getValueAt(selection, 0).toString().replaceAll("\\s", ""));
            DialogoBusquedaTabla.txtDescripcionSublinea.setText(jtableSubLinea.getValueAt(selection, 1).toString().replaceAll("\\s", ""));
            dispose();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Debe Seleccionar una linea", "Software", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarSubLineaActionPerformed
    public void pObtenerListadoDatosSubLinea(String sDatabase_Name, String sTable_Name, String sField_Name, String sValor, String iOpcion, String sCo_lin) {
        ArrayList<SubLineaBO> lista = new SublineaModel().pObtenerListadoDatosSubLinea(sDatabase_Name, sTable_Name, sField_Name, sValor, iOpcion, sCo_lin);
        if (lista.size() == 0) {
            JOptionPane.showMessageDialog(new JFrame(), "No se encontraron sublineas para este articulo", "Software", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (lista.size() != 0) {
            jtableSubLinea.setModel(new ModeloTablaSubLinea(lista));
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogoBusquedaAsistida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogoBusquedaAsistida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogoBusquedaAsistida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogoBusquedaAsistida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogoBusquedaAsistida dialog = new JDialogoBusquedaAsistida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarSubLinea;
    public javax.swing.JButton btnCancelarSubLinea;
    private javax.swing.ButtonGroup btnGrupoBusqueda;
    private javax.swing.ButtonGroup btnGrupoOpcion;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    public javax.swing.JRadioButton jRFinal4;
    public javax.swing.JRadioButton jRInicio4;
    public javax.swing.JRadioButton jRexacta4;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JRadioButton jrCodigo4;
    public javax.swing.JRadioButton jrCualquier4;
    public javax.swing.JRadioButton jrDescripcion4;
    public javax.swing.JTable jtableSubLinea;
    public javax.swing.JTextField txtBuscarValorSubLinea;
    // End of variables declaration//GEN-END:variables
}
