package Vista;

import evento.VistaPrincipalevent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author earana
 */
public class Vistaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalTest
     */
    public static String nombreUsuario = "null";
    VistaPrincipalevent controller;
    public static String tempUsuario,tempEmpresa,tempSucrsal;

    public Vistaprincipal() {
        initComponents();
        controller = new VistaPrincipalevent(this);
        btnArticulo.addActionListener(controller);
        btnlinea.addActionListener(controller);
        btnSublinea.addActionListener(controller);
        btnCategoria.addActionListener(controller);
        btnColor.addActionListener(controller);
        btnUnidad.addActionListener(controller);
        btnUbicacion.addActionListener(controller);
        btnSucursal.addActionListener(controller);
        btnProcedencia.addActionListener(controller);
        btnProveedor.addActionListener(controller);
        btnTipoAjuste.addActionListener(controller);
        btnAlmacen.addActionListener(controller);
        btnUsuario.addActionListener(controller);
        btnAjusteES.addActionListener(controller);
        btnAbriCerrar.addActionListener(controller);
        btnResultado.addActionListener(controller);
        btnProveedorCompras.addActionListener(controller);
        btnTipoClienteVCxC.addActionListener(controller);
        btnClienteVCxC.addActionListener(controller);
        btnAlmacenVCxC.addActionListener(controller); 
        btnPaisVCxC.addActionListener(controller);
        btnSegmentoVCxC.addActionListener(controller);
        btnZonaVCxC.addActionListener(controller);
        btnSegmentoCxP.addActionListener(controller);
        btnZonaCxP.addActionListener(controller);
        btnTipoComprasCxP.addActionListener(controller);
        btnCuntaIngresoEgresoCxP.addActionListener(controller);
        btnCondicionPagoVCxC.addActionListener(controller);
        btnCotizacionVeCXC.addActionListener(controller);
        btnfacturaVentaCxC.addActionListener(controller);
        btnNotaEntregaVenCxC.addActionListener(controller);
        btnDevolucionVCxC.addActionListener(controller);
        lblNombreEmpresa.setText(tempEmpresa);
        lblNombreUsuario1.setText(tempUsuario);
        lblNombreSucursal.setText(tempSucrsal);
        btnMoneda.addActionListener(controller);
        jMSalir.addActionListener(controller);
        btnTransporteVCxC.addActionListener(controller);
        btnVendedor.addActionListener(controller);
        btnCondicionPagoCxP.addActionListener(controller);
        btnTabulador.addActionListener(controller);
        btnCxCDespacho.addActionListener(controller);
        btnIVATributario.addActionListener(controller);
        btnFacturaCompra.addActionListener(controller);
        btnBanco.addActionListener(controller);
        btnBeneficiario.addActionListener(controller);
     
        System.out.println("Datos Empresa:" +tempEmpresa+ " \n "
                + "Usuario " +tempUsuario +"\n"
                +"Suscursal " +tempSucrsal
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblEmpresa = new javax.swing.JLabel();
        nameEmpresa = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        lblNombreEmpresa = new javax.swing.JLabel();
        lblNombreSucursal = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblNombreUsuario1 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanelInventario = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnArticulo = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnUnidad = new javax.swing.JButton();
        btnlinea = new javax.swing.JButton();
        btnSublinea = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAlmacen = new javax.swing.JButton();
        btnUbicacion = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnTipoAjuste = new javax.swing.JButton();
        btnProcedencia = new javax.swing.JButton();
        btnSucursal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAjusteES = new javax.swing.JButton();
        btnAbriCerrar = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        Mantenimiento = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        jpaneTributario = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        btnMoneda = new javax.swing.JButton();
        btnUniTirbutaria = new javax.swing.JButton();
        btnTabulador = new javax.swing.JButton();
        btnConcepto = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        btnIVATributario = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        btnExtraerDatos = new javax.swing.JButton();
        btnMunicipal = new javax.swing.JButton();
        btnAdicional = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnfacturaVentaCxC = new javax.swing.JButton();
        btnCotizacionVeCXC = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnNotaEntregaVenCxC = new javax.swing.JButton();
        btnDevolucionVCxC = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCxCDespacho = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnDocumentoVen = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnClienteVCxC = new javax.swing.JButton();
        btnTipoClienteVCxC = new javax.swing.JButton();
        btnZonaVCxC = new javax.swing.JButton();
        btnSegmentoVCxC = new javax.swing.JButton();
        btnPaisVCxC = new javax.swing.JButton();
        btnAlmacenVCxC = new javax.swing.JButton();
        btnSucursalVCxC = new javax.swing.JButton();
        btnTransporteVCxC = new javax.swing.JButton();
        btnCondicionPagoVCxC = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnFacturaCompra = new javax.swing.JButton();
        btnOrdenCompra = new javax.swing.JButton();
        btnCotizacionCompra = new javax.swing.JButton();
        btnDevolucionCompra = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnPlantilla = new javax.swing.JButton();
        btnProgramacionPago = new javax.swing.JButton();
        btnPagoCompra = new javax.swing.JButton();
        btnDocumentoCompras = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnDocElectronic = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnProveedorCompras = new javax.swing.JButton();
        btnTipoComprasCxP = new javax.swing.JButton();
        btnZonaCxP = new javax.swing.JButton();
        btnSegmentoCxP = new javax.swing.JButton();
        btnCondicionPagoCxP = new javax.swing.JButton();
        btnCuntaIngresoEgresoCxP = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        btnBanco = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        btnBeneficiario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software Administrativo");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpresa.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmpresa.setText("Empresa :");
        jPanel3.add(lblEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, -1));
        jPanel3.add(nameEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 64, -1));

        lblSucursal.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblSucursal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSucursal.setText("Sucursal :");
        jPanel3.add(lblSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 82, -1));
        jPanel3.add(lblNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, -3, 180, 20));
        jPanel3.add(lblNombreSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 150, 20));

        lblUsuario1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario1.setText("Usuario :");
        jPanel3.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 82, -1));
        jPanel3.add(lblNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 150, 20));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jpanelInventario.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/articulo.png"))); // NOI18N
        btnArticulo.setText("Articulo");
        btnArticulo.setToolTipText("Articulo");
        jPanel1.add(btnArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 1, 112, 40));

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categoria.png"))); // NOI18N
        btnCategoria.setText("Categoria");
        btnCategoria.setToolTipText("Categoria");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 1, -1, 40));

        btnUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unidad.png"))); // NOI18N
        btnUnidad.setText("Unidad");
        btnUnidad.setToolTipText("Unidad");
        jPanel1.add(btnUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 47, 115, 40));

        btnlinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lineas_1.png"))); // NOI18N
        btnlinea.setText("linea");
        btnlinea.setToolTipText("Linea");
        jPanel1.add(btnlinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 47, 112, 40));

        btnSublinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subLineas_1.png"))); // NOI18N
        btnSublinea.setText("SubLinea");
        btnSublinea.setToolTipText("Sub -Linea");
        jPanel1.add(btnSublinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 93, -1, 40));

        btnColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/color_1.png"))); // NOI18N
        btnColor.setText("Color");
        btnColor.setToolTipText("Color");
        jPanel1.add(btnColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 93, 115, 40));

        jpanelInventario.add(jPanel1);
        jPanel1.setBounds(5, 0, 250, 140);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/almacen.png"))); // NOI18N
        btnAlmacen.setText("Almacen");
        btnAlmacen.setToolTipText("Almacen");
        jPanel2.add(btnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        btnUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ubicacion.png"))); // NOI18N
        btnUbicacion.setText("Ubicacion");
        btnUbicacion.setToolTipText("Ubicacion");
        jPanel2.add(btnUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedor.png"))); // NOI18N
        btnProveedor.setText("Proveedor");
        btnProveedor.setToolTipText("Proveedor");
        jPanel2.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 40));

        btnTipoAjuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipoAjuste.png"))); // NOI18N
        btnTipoAjuste.setText("tipo Ajuste");
        btnTipoAjuste.setToolTipText("Tipo de Ajuste");
        jPanel2.add(btnTipoAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 130, 40));

        btnProcedencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/procedenci.png"))); // NOI18N
        btnProcedencia.setText("Procedencia");
        jPanel2.add(btnProcedencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 40));

        btnSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subcursal.png"))); // NOI18N
        btnSucursal.setText("Sucursal");
        btnSucursal.setToolTipText("Sucursal");
        jPanel2.add(btnSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, 40));

        jpanelInventario.add(jPanel2);
        jPanel2.setBounds(260, 0, 280, 140);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAjusteES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ajustest.png"))); // NOI18N
        btnAjusteES.setText("Ajustes");
        btnAjusteES.setToolTipText("Ajustes Entrada Salidas");
        jPanel4.add(btnAjusteES, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 35));

        btnAbriCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicCerrar.png"))); // NOI18N
        btnAbriCerrar.setText("Iniciar/Cerrar");
        jPanel4.add(btnAbriCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 53, 112, 32));

        btnResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resultados.png"))); // NOI18N
        btnResultado.setText("Resultado");
        jPanel4.add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 31));

        jpanelInventario.add(jPanel4);
        jPanel4.setBounds(550, 0, 140, 140);

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablas", "Almacenes", "Artículos Compuestos", "Categorías", "Colores", "Lineas", "Procedencias", "Sub-Lineas", "Sucursales", "Tipos de Ajustes", "Ubicaciones", "Unidades" }));
        jPanel7.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ajustes", "Ajustes de Entrada y Salida" }));
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Precios y Costos", "Ajustes de Precios y Costos" }));
        jPanel7.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artículos", "Artículos Con su Stock" }));
        jPanel7.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inventarios Fisíco", "Inventarios" }));
        jPanel7.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, -1));

        jpanelInventario.add(jPanel7);
        jPanel7.setBounds(700, 0, 280, 140);

        jTabbedPane1.addTab("Inventario", jpanelInventario);

        Mantenimiento.setLayout(null);

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_48px.png"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setToolTipText("Usuario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Mantenimiento.add(jPanel5);
        jPanel5.setBounds(0, 0, 195, 140);

        jTabbedPane1.addTab("Mantenimiento", Mantenimiento);

        jpaneTributario.setLayout(null);

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnMoneda.setText("Moneda");

        btnUniTirbutaria.setText("Unidad Tributaria");

        btnTabulador.setText("Tabulador");

        btnConcepto.setText("Concepto");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btnUniTirbutaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTabulador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUniTirbutaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTabulador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnConcepto))
        );

        jpaneTributario.add(jPanel15);
        jPanel15.setBounds(0, 0, 190, 140);

        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnIVATributario.setText("I.V.A");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIVATributario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIVATributario, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jpaneTributario.add(jPanel17);
        jPanel17.setBounds(200, 0, 90, 140);

        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnExtraerDatos.setText("Extr  Datos");
        btnExtraerDatos.setToolTipText("Extraer Datos");

        btnMunicipal.setText("Municipal");
        btnMunicipal.setToolTipText("");

        btnAdicional.setText("Adicional");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExtraerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMunicipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExtraerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnMunicipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicional)
                .addGap(34, 34, 34))
        );

        jpaneTributario.add(jPanel18);
        jPanel18.setBounds(300, 0, 220, 140);

        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel19.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jpaneTributario.add(jPanel19);
        jPanel19.setBounds(530, 0, 240, 140);

        jTabbedPane1.addTab("Tributario", jpaneTributario);

        jPanel6.setLayout(null);

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnfacturaVentaCxC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura2.png"))); // NOI18N
        btnfacturaVentaCxC.setText("Factura");
        btnfacturaVentaCxC.setToolTipText("Factura Venta");
        jPanel11.add(btnfacturaVentaCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 26, -1, 81));

        btnCotizacionVeCXC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cotizacion.png"))); // NOI18N
        btnCotizacionVeCXC.setText("Cotizacion");
        btnCotizacionVeCXC.setToolTipText("Cotizacion");
        jPanel11.add(btnCotizacionVeCXC, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 12, 140, 40));

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pedido.png"))); // NOI18N
        btnPedido.setText("Pedido");
        btnPedido.setToolTipText("Pedidos");
        jPanel11.add(btnPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 58, 140, 40));

        btnNotaEntregaVenCxC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notaentrega.png"))); // NOI18N
        btnNotaEntregaVenCxC.setText("Nota Entrega");
        btnNotaEntregaVenCxC.setToolTipText("Nota de Enrtrega");
        jPanel11.add(btnNotaEntregaVenCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 105, 140, 35));

        btnDevolucionVCxC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devolution.png"))); // NOI18N
        btnDevolucionVCxC.setText("Devolucion");
        btnDevolucionVCxC.setToolTipText("Devolucion");
        jPanel11.add(btnDevolucionVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 12, 133, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantilla.png"))); // NOI18N
        jButton2.setText("plantilla");
        jButton2.setToolTipText("plantilla");
        jPanel11.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 58, 133, 40));

        btnCxCDespacho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/despacho.png"))); // NOI18N
        btnCxCDespacho.setText("Despacho");
        btnCxCDespacho.setToolTipText("Despacho");
        jPanel11.add(btnCxCDespacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 105, 133, 35));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobro.png"))); // NOI18N
        jButton4.setText("Cobro");
        jButton4.setToolTipText("Cobros");
        jPanel11.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 12, 112, 40));

        btnDocumentoVen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnDocumentoVen.setText("document");
        btnDocumentoVen.setToolTipText("Documentos");
        jPanel11.add(btnDocumentoVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 58, 112, -1));

        jPanel6.add(jPanel11);
        jPanel11.setBounds(0, 0, 520, 140);

        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClienteVCxC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        btnClienteVCxC.setText("Cliente");
        btnClienteVCxC.setToolTipText("Cliente");
        jPanel12.add(btnClienteVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 100));

        btnTipoClienteVCxC.setText("Tipo");
        btnTipoClienteVCxC.setToolTipText("Tipo Proveedor");
        jPanel12.add(btnTipoClienteVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, -1));

        btnZonaVCxC.setText("Zona");
        btnZonaVCxC.setToolTipText("Zona");
        jPanel12.add(btnZonaVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, -1));

        btnSegmentoVCxC.setText("Segmento");
        btnSegmentoVCxC.setToolTipText("Segmento");
        jPanel12.add(btnSegmentoVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        btnPaisVCxC.setText("Pais");
        btnPaisVCxC.setToolTipText("Pais");
        jPanel12.add(btnPaisVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, -1));

        btnAlmacenVCxC.setText("Almacen");
        btnAlmacenVCxC.setToolTipText("Almacen");
        jPanel12.add(btnAlmacenVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 120, -1));

        btnSucursalVCxC.setText("Sucursal");
        btnSucursalVCxC.setToolTipText("Sucursal");
        jPanel12.add(btnSucursalVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 120, -1));

        btnTransporteVCxC.setText("Transporte");
        btnTransporteVCxC.setToolTipText("Transporte");
        jPanel12.add(btnTransporteVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 120, -1));

        btnCondicionPagoVCxC.setText("Condicion Pago");
        jPanel12.add(btnCondicionPagoVCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 120, -1));

        btnVendedor.setText("Vendedor");
        jPanel12.add(btnVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 10, 110, -1));

        jPanel6.add(jPanel12);
        jPanel12.setBounds(530, 0, 480, 140);

        jTabbedPane1.addTab("Venta y CXC", jPanel6);

        jPanel8.setLayout(null);

        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFacturaCompra.setText("Factura");
        btnFacturaCompra.setToolTipText("Factura");
        jPanel9.add(btnFacturaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 80));

        btnOrdenCompra.setText("Orden Compra");
        btnOrdenCompra.setToolTipText("Orden de Compras");
        jPanel9.add(btnOrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, -1));

        btnCotizacionCompra.setText("Cotizacion");
        btnCotizacionCompra.setToolTipText("Cotizacion");
        jPanel9.add(btnCotizacionCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, -1));

        btnDevolucionCompra.setText("Devolucion");
        btnDevolucionCompra.setToolTipText("Devolucion");
        jPanel9.add(btnDevolucionCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, -1));

        jButton9.setText("Nota de Recepcion");
        jPanel9.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, -1));

        btnPlantilla.setText("Plantilla");
        btnPlantilla.setToolTipText("Plantilla");
        jPanel9.add(btnPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 140, -1));

        btnProgramacionPago.setText("Programacion Pago");
        btnProgramacionPago.setToolTipText("Programacion Pago");
        jPanel9.add(btnProgramacionPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, -1));

        btnPagoCompra.setText("Pago");
        btnPagoCompra.setToolTipText("Pago");
        jPanel9.add(btnPagoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, -1));

        btnDocumentoCompras.setText("Documento");
        btnDocumentoCompras.setToolTipText("Documento");
        jPanel9.add(btnDocumentoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 140, -1));

        jButton6.setText("Generar Giro");
        jPanel9.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 140, -1));

        btnDocElectronic.setText("Docm. Electr");
        jPanel9.add(btnDocElectronic, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 140, -1));

        jPanel8.add(jPanel9);
        jPanel9.setBounds(0, 0, 520, 140);

        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProveedorCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipoProveedor.png"))); // NOI18N
        btnProveedorCompras.setText("Proveedor");
        btnProveedorCompras.setToolTipText("Proveedor");
        jPanel10.add(btnProveedorCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 120, 80));

        btnTipoComprasCxP.setText("tipo");
        btnTipoComprasCxP.setToolTipText("Tipo");
        jPanel10.add(btnTipoComprasCxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, -1));

        btnZonaCxP.setText("Zona");
        btnZonaCxP.setToolTipText("Zona");
        jPanel10.add(btnZonaCxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));

        btnSegmentoCxP.setText("Segmento");
        btnSegmentoCxP.setToolTipText("Segmento");
        jPanel10.add(btnSegmentoCxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, -1));

        btnCondicionPagoCxP.setText("Cond Pago");
        btnCondicionPagoCxP.setToolTipText("Condicion de pago");
        jPanel10.add(btnCondicionPagoCxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        btnCuntaIngresoEgresoCxP.setText("Cuenta In/Egre");
        btnCuntaIngresoEgresoCxP.setToolTipText("Cuenta Ingreso/Egreso");
        jPanel10.add(btnCuntaIngresoEgresoCxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, -1));

        jPanel8.add(jPanel10);
        jPanel10.setBounds(530, 0, 370, 140);

        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel13);
        jPanel13.setBounds(910, 0, 70, 140);

        jTabbedPane1.addTab("Compra y CxP", jPanel8);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print_26px.png"))); // NOI18N
        jButton5.setText("Mov.Caja");
        jPanel16.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, 40));

        btnBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento banco.png"))); // NOI18N
        btnBanco.setText("Banco");
        jPanel16.add(btnBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Deposito.png"))); // NOI18N
        jButton7.setText("Deposito");
        jPanel16.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 140, 40));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden de pago.png"))); // NOI18N
        jButton8.setText("Ord. Pago");
        jPanel16.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/transferencia cuenta.png"))); // NOI18N
        jButton10.setText("Trans. Cuentas");
        jPanel16.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrega de cheque.png"))); // NOI18N
        jButton11.setText("Entr. Cheque");
        jPanel16.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 140, 40));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 120));

        btnBeneficiario.setText("Beneficiario");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBeneficiario)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 340, 120));

        jTabbedPane1.addTab("Caja y Banco", jPanel14);

        jMenu1.setText("File");

        jMSalir.setText("Salir");
        jMenu1.add(jMSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
            .addComponent(escritorio)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mantenimiento;
    public javax.swing.JButton btnAbriCerrar;
    public javax.swing.JButton btnAdicional;
    public javax.swing.JButton btnAjusteES;
    public javax.swing.JButton btnAlmacen;
    public javax.swing.JButton btnAlmacenVCxC;
    public javax.swing.JButton btnArticulo;
    public javax.swing.JButton btnBanco;
    public javax.swing.JButton btnBeneficiario;
    public javax.swing.JButton btnCategoria;
    public javax.swing.JButton btnClienteVCxC;
    public javax.swing.JButton btnColor;
    public javax.swing.JButton btnConcepto;
    public javax.swing.JButton btnCondicionPagoCxP;
    public javax.swing.JButton btnCondicionPagoVCxC;
    public javax.swing.JButton btnCotizacionCompra;
    public javax.swing.JButton btnCotizacionVeCXC;
    public javax.swing.JButton btnCuntaIngresoEgresoCxP;
    public javax.swing.JButton btnCxCDespacho;
    public javax.swing.JButton btnDevolucionCompra;
    public javax.swing.JButton btnDevolucionVCxC;
    public javax.swing.JButton btnDocElectronic;
    public javax.swing.JButton btnDocumentoCompras;
    public javax.swing.JButton btnDocumentoVen;
    public javax.swing.JButton btnExtraerDatos;
    public javax.swing.JButton btnFacturaCompra;
    public javax.swing.JButton btnIVATributario;
    public javax.swing.JButton btnMoneda;
    public javax.swing.JButton btnMunicipal;
    public javax.swing.JButton btnNotaEntregaVenCxC;
    public javax.swing.JButton btnOrdenCompra;
    public javax.swing.JButton btnPagoCompra;
    public javax.swing.JButton btnPaisVCxC;
    public javax.swing.JButton btnPedido;
    public javax.swing.JButton btnPlantilla;
    public javax.swing.JButton btnProcedencia;
    public javax.swing.JButton btnProgramacionPago;
    public javax.swing.JButton btnProveedor;
    public javax.swing.JButton btnProveedorCompras;
    public javax.swing.JButton btnResultado;
    public javax.swing.JButton btnSegmentoCxP;
    public javax.swing.JButton btnSegmentoVCxC;
    public javax.swing.JButton btnSublinea;
    public javax.swing.JButton btnSucursal;
    public javax.swing.JButton btnSucursalVCxC;
    public javax.swing.JButton btnTabulador;
    public javax.swing.JButton btnTipoAjuste;
    public javax.swing.JButton btnTipoClienteVCxC;
    public javax.swing.JButton btnTipoComprasCxP;
    public javax.swing.JButton btnTransporteVCxC;
    public javax.swing.JButton btnUbicacion;
    public javax.swing.JButton btnUniTirbutaria;
    public javax.swing.JButton btnUnidad;
    public javax.swing.JButton btnUsuario;
    public javax.swing.JButton btnVendedor;
    public javax.swing.JButton btnZonaCxP;
    public javax.swing.JButton btnZonaVCxC;
    public javax.swing.JButton btnfacturaVentaCxC;
    public javax.swing.JButton btnlinea;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    public javax.swing.JMenuItem jMSalir;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpaneTributario;
    private javax.swing.JPanel jpanelInventario;
    public javax.swing.JLabel lblEmpresa;
    public static javax.swing.JLabel lblNombreEmpresa;
    public static javax.swing.JLabel lblNombreSucursal;
    public static javax.swing.JLabel lblNombreUsuario1;
    public javax.swing.JLabel lblSucursal;
    public javax.swing.JLabel lblUsuario1;
    public javax.swing.JLabel nameEmpresa;
    // End of variables declaration//GEN-END:variables
}
