/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import VistaDialogos.DialogoBusquedaTabla;
import Beans.LineaBO;
import Beans.SubLineaBO;
import Controller.SubLineaController;
import Model.LineaModel;
import Model.ModeloTablaSubLinea;
import Model.SublineaModel;
import java.sql.SQLException;
import java.util.ArrayList;
import Atxy2k.CustomTextField.RestrictedTextField; 
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author earana
 */
public class VistaSublinea extends javax.swing.JPanel {

    SubLineaController controller;
    ArrayList<LineaBO> listaLinea;
    LineaModel lineamodelo;
    SublineaModel sublineaModel;

    /**
     * Creates new form VistaSublinea
     */
    public VistaSublinea() {
        initComponents();
        RestrictedTextField re = new RestrictedTextField(txtcodigoSubLinea);
        // re.setOnlyText(true);
        re.setAcceptSpace(true);
        re.setLimit(6);
        controller = new SubLineaController(this);
        btnBuscar.addActionListener(controller);
        btnGuardar.addActionListener(controller);
        btnEliminar.addActionListener(controller);
        btnactulizar.addActionListener(controller);
        btnNuevo.addActionListener(controller);

        btnAceptarSubLinea.addActionListener(controller);
        btnCancelarSubLinea.addActionListener(controller);

        listaLinea = new ArrayList<LineaBO>();
        lineamodelo = new LineaModel();
        sublineaModel = new SublineaModel();

        try {
            listaLinea = lineamodelo.listaLineas();
            for (int c = 0; c < listaLinea.size(); c++) {
                seletLinea.addItem(listaLinea.get(c).getLin_des());
            }
            setModel();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setModel() throws SQLException {
        jtableSubLinea.setModel(new ModeloTablaSubLinea(sublineaModel.listaSubLineas()));

    }

    public void setterCampos() {
        txtCampo1.setText("");
        txtCodgimpuestoMunicipal.setText("");
        txtDescripImpMunicipal.setText("");
        txtDescripcionSubLinea.setText("");
        txtcampo2.setText("");
        txtcodigoSubLinea.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogSubLinea = new javax.swing.JDialog();
        txtBuscarValorSubLinea = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtableSubLinea = new javax.swing.JTable();
        btnAceptarSubLinea = new javax.swing.JButton();
        btnCancelarSubLinea = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jrCodigo4 = new javax.swing.JRadioButton();
        jrDescripcion4 = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        jRInicio4 = new javax.swing.JRadioButton();
        jRFinal4 = new javax.swing.JRadioButton();
        jrCualquier4 = new javax.swing.JRadioButton();
        jRexacta4 = new javax.swing.JRadioButton();
        btngrupoOpcion = new javax.swing.ButtonGroup();
        btnGrupoBusqueda = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnactulizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        txtCodgimpuestoMunicipal = new javax.swing.JTextField();
        txtcodigoSubLinea = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblComisonVentas = new javax.swing.JLabel();
        lblImpuestoMunicipal = new javax.swing.JLabel();
        txtDescripcionSubLinea = new javax.swing.JTextField();
        txtDescripImpMunicipal = new javax.swing.JTextField();
        seletLinea = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCampo1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcampo2 = new javax.swing.JTextField();

        jDialogSubLinea.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarValorSubLinea.setToolTipText("Buscar");
        jDialogSubLinea.getContentPane().add(txtBuscarValorSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, -1));

        jLabel28.setText("Buscar :");
        jDialogSubLinea.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jtableSubLinea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jtableSubLinea);

        jDialogSubLinea.getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 120));

        btnAceptarSubLinea.setText("Aceptar");
        jDialogSubLinea.getContentPane().add(btnAceptarSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 98, -1));

        btnCancelarSubLinea.setText("Cancelar");
        btnCancelarSubLinea.setToolTipText("Cancelar");
        jDialogSubLinea.getContentPane().add(btnCancelarSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, -1));

        jLabel29.setText("Total de Registros Encontrados");
        jDialogSubLinea.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 180, -1));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));

        btnGrupoBusqueda.add(jrCodigo4);
        jrCodigo4.setSelected(true);
        jrCodigo4.setText("Codigo");
        jrCodigo4.setToolTipText("Codigo");

        btnGrupoBusqueda.add(jrDescripcion4);
        jrDescripcion4.setText("Descripcion");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrDescripcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jrCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jrCodigo4)
                .addGap(18, 18, 18)
                .addComponent(jrDescripcion4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jDialogSubLinea.getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 100));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion"));

        btngrupoOpcion.add(jRInicio4);
        jRInicio4.setText("1) Inicio");
        jRInicio4.setToolTipText("Coincida al inicio");

        btngrupoOpcion.add(jRFinal4);
        jRFinal4.setText("2)Final");
        jRFinal4.setToolTipText("Coincida al Final");

        btngrupoOpcion.add(jrCualquier4);
        jrCualquier4.setSelected(true);
        jrCualquier4.setText("3)Cualquier");
        jrCualquier4.setToolTipText("Cualquier Caracter");

        btngrupoOpcion.add(jRexacta4);
        jRexacta4.setText("4)exacta");
        jRexacta4.setToolTipText("Exacta Caracter");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRFinal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jrCualquier4)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jRInicio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jRexacta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jRInicio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFinal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrCualquier4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRexacta4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jDialogSubLinea.getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 130));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNuevo);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_icon.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnactulizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        btnactulizar.setToolTipText("actualizar");
        btnactulizar.setFocusable(false);
        btnactulizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnactulizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnactulizar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_1.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEliminar);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_1.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuscar);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir_1.png"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnImprimir);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 50));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescripcion.setText("Descripcion :");
        jPanel2.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, -1));

        txtCodgimpuestoMunicipal.setToolTipText("Impuesto Municipal");
        jPanel2.add(txtCodgimpuestoMunicipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));

        txtcodigoSubLinea.setColumns(6);
        txtcodigoSubLinea.setToolTipText("Codigo");
        jPanel2.add(txtcodigoSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigo.setText("Codigo :");
        jPanel2.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));

        lblComisonVentas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblComisonVentas.setText("Linea:");
        lblComisonVentas.setToolTipText("");
        jPanel2.add(lblComisonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, -1));

        lblImpuestoMunicipal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImpuestoMunicipal.setText("impuesto municipal :");
        lblImpuestoMunicipal.setToolTipText("");
        jPanel2.add(lblImpuestoMunicipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        txtDescripcionSubLinea.setToolTipText("Descripcion Linea");
        jPanel2.add(txtDescripcionSubLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 330, -1));

        txtDescripImpMunicipal.setToolTipText("");
        jPanel2.add(txtDescripImpMunicipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 220, -1));

        jPanel2.add(seletLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 330, -1));

        jTabbedPane1.addTab("Datos Basicos", jPanel2);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Campo1 :");
        jLabel4.setToolTipText("");

        txtCampo1.setToolTipText("campo1");

        jLabel3.setText("Campo2:");

        txtcampo2.setToolTipText("Campo 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtcampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Adicionales", jPanel3);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 680, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        DialogoBusquedaTabla n = new DialogoBusquedaTabla(new JFrame(), true);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = d.width / 3;
        int alto = d.height / 4;
        n.setSize(ancho, alto);
        n.setLocationRelativeTo(null);
        n.setVisible(true);

        // calculamos el tamaño de la ventana a partir del ancho de la pantalla
        // jDialogSubLinea.setVisible(true);
        //jDialogSubLinea.setModal(true);
//        jDialogSubLinea.setSize(472, 358);
//        jDialogSubLinea.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarSubLinea;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelarSubLinea;
    public static javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrupoBusqueda;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnImprimir;
    public javax.swing.JButton btnNuevo;
    public static javax.swing.JButton btnactulizar;
    private javax.swing.ButtonGroup btngrupoOpcion;
    public javax.swing.JDialog jDialogSubLinea;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JRadioButton jRFinal4;
    public javax.swing.JRadioButton jRInicio4;
    public javax.swing.JRadioButton jRexacta4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JRadioButton jrCodigo4;
    public javax.swing.JRadioButton jrCualquier4;
    public javax.swing.JRadioButton jrDescripcion4;
    public javax.swing.JTable jtableSubLinea;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblComisonVentas;
    public javax.swing.JLabel lblDescripcion;
    public javax.swing.JLabel lblImpuestoMunicipal;
    public static javax.swing.JComboBox seletLinea;
    public javax.swing.JTextField txtBuscarValorSubLinea;
    public javax.swing.JTextField txtCampo1;
    public static javax.swing.JTextField txtCodgimpuestoMunicipal;
    public static javax.swing.JTextField txtDescripImpMunicipal;
    public static javax.swing.JTextField txtDescripcionSubLinea;
    public javax.swing.JTextField txtcampo2;
    public static javax.swing.JTextField txtcodigoSubLinea;
    // End of variables declaration//GEN-END:variables
}
