/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.FacturaCompraController;
import java.util.Date;

/**
 *
 * @author aranaVentur
 */
public class VistaFacturaCompras extends javax.swing.JPanel {

    /**
     * Creates new form VistaFacturaCompras
     */
    FacturaCompraController controller;
public static int FILA_jtablaComprasreng = 0;
    public VistaFacturaCompras() {
        initComponents();
        jLabelAnulado.setVisible(false);
        fechaFacturaActual.setDate(new Date());
        fechaRegistro.setDate(new Date());
        fechaVencimiento.setDate(new Date());
        controller = new FacturaCompraController(this);
        controller.cargarDatosFacturaCompraRenglon("");
        btnBuscar.addActionListener(controller);
        btnGuardar.addActionListener(controller);
        btnAceptarFactCompra.addActionListener(controller);
        txtBuscarFactCompra.addKeyListener(controller);
        btnCancelarFacturaCompra.addActionListener(controller);
        btnactulizar.addActionListener(controller);
        btnNuevo.addActionListener(controller);
        btnEliminar.addActionListener(controller);
        btnagregar.addActionListener(controller);
        btnrestar.addActionListener(controller);
        txtcdiProveedor.addKeyListener(controller);
        txtCodPago.addKeyListener(controller);
        txtCodMoneda.addKeyListener(controller);
        btnAceptarMonedas.addActionListener(controller);
        btnCancelarCondicionPag.addActionListener(controller);
        btnCancelarmonedas.addActionListener(controller);
        txtBuscarProveedor.addKeyListener(controller);
        btnAceptarDialoProv.addActionListener(controller);
       btnAceptarCondicionPag.addActionListener(controller);
       jTablaFacturaCompraRenglon.setCellSelectionEnabled(true);
        jTablaFacturaCompraRenglon.addKeyListener(controller);
    }
    
    public void setterCampos() {
        TxtCampo1.setText("");
        TxtCampo2.setText("");
        TxtCampo3.setText("");
        TxtCampo4.setText("");
        TxtCampo5.setText("");
        TxtCampo6.setText("");
        TxtDescripcionCodPago.setText("");
        TxtDireccionEntrega.setText("");
        txtCodMoneda.setText("");
        txtNumDocumentCompra.setText("");
        txtcdiProveedor.setText("");
        txtCodPago.setText("");
        txtNumFactura.setText("");
        txtNmControl.setText("");
        txtDescripcionFactCompra.setText("");
        fechaFacturaActual.setDate(new Date());
        fechaVencimiento.setDate(new Date());
        fechaRegistro.setDate(new Date());
        TxtMoneda2.setText("");
        txtDescripcionProveedor.setText("");
        txtTasa.setText("0");
        txtDescuesto.setText("0");
        txtMontoDescuentoGlobal.setText("0");
        txtSubTotalBruto.setText("0");
        txtRec.setText("0");
        txtMontoporc_recal.setText("0");
        txtImpuesto.setText("0");
        txtOtros.setText("0");
        txtTotalNeto.setText("0");
        txtSaldo.setText("0");
        btnGuardar.setEnabled(true);
        btnactulizar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogFActuraCompra = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        txtBuscarFactCompra = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtablaFacturaCompra = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jRInicio = new javax.swing.JRadioButton();
        jRFinal = new javax.swing.JRadioButton();
        jrCualquier = new javax.swing.JRadioButton();
        JRExacta = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jrCodigo2 = new javax.swing.JRadioButton();
        jrCliente = new javax.swing.JRadioButton();
        btnAceptarFactCompra = new javax.swing.JButton();
        btnCancelarFacturaCompra = new javax.swing.JButton();
        btnGrupoOpcion = new javax.swing.ButtonGroup();
        btnGrupoBusqueda = new javax.swing.ButtonGroup();
        jDialogProveedor = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablaProveedores = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jRInicioProv = new javax.swing.JRadioButton();
        jRFinalProv = new javax.swing.JRadioButton();
        jrCualquierProv = new javax.swing.JRadioButton();
        jRexactaProv = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jrCodigo = new javax.swing.JRadioButton();
        jrDescripcion = new javax.swing.JRadioButton();
        btnAceptarDialoProv = new javax.swing.JButton();
        btnCancelarProv = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        txtBuscarProveedor = new javax.swing.JTextField();
        jDialogCondPago = new javax.swing.JDialog();
        jLabel35 = new javax.swing.JLabel();
        txtValorCondicionPago = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablaCondicionPago = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jRInicioCondPago = new javax.swing.JRadioButton();
        jRFinalCondPago = new javax.swing.JRadioButton();
        jrCualquierCondPago = new javax.swing.JRadioButton();
        jRexactaCondPago = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jrCodigoCondPago = new javax.swing.JRadioButton();
        jrDescripcionCondPago = new javax.swing.JRadioButton();
        btnAceptarCondicionPag = new javax.swing.JButton();
        btnCancelarCondicionPag = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jDialogMoneda = new javax.swing.JDialog();
        jLabel37 = new javax.swing.JLabel();
        txtBuscarMoneda = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtableMonedas = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jRInicioMoneda = new javax.swing.JRadioButton();
        jRFinalMoneda = new javax.swing.JRadioButton();
        jrCualquierMoneda = new javax.swing.JRadioButton();
        jRexactaMoneda = new javax.swing.JRadioButton();
        jPanel17 = new javax.swing.JPanel();
        jrCodigoMoneda = new javax.swing.JRadioButton();
        jrDescripcionMoneda = new javax.swing.JRadioButton();
        btnAceptarMonedas = new javax.swing.JButton();
        btnCancelarmonedas = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        btnGrupoOpcionCondPago = new javax.swing.ButtonGroup();
        btnGrupoBusqudaProv = new javax.swing.ButtonGroup();
        btnGrupoOpcioProv = new javax.swing.ButtonGroup();
        jToolBar2 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnactulizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btnrestar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodPago = new javax.swing.JTextField();
        TxtDescripcionCodPago = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        txtNmControl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCodMoneda = new javax.swing.JTextField();
        TxtMoneda2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTasa = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaFacturaCompraRenglon = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        txtMontoIGTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDescuesto = new javax.swing.JTextField();
        txtMontoDescuentoGlobal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRec = new javax.swing.JTextField();
        txtMontoporc_recal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSubTotalBruto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtOtros = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTotalNeto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fechaRegistro = new com.toedter.calendar.JDateChooser();
        fechaFacturaActual = new com.toedter.calendar.JDateChooser();
        fechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        txtNumDocumentCompra = new javax.swing.JTextField();
        txtcdiProveedor = new javax.swing.JTextField();
        txtDescripcionProveedor = new javax.swing.JTextField();
        txtDescripcionFactCompra = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelAnulado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        TxtDireccionEntrega = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxtCampo1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        TxtCampo2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TxtCampo3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TxtCampo4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        TxtCampo5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TxtCampo6 = new javax.swing.JTextField();
        txtCuentIngEgr = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();

        jDialogFActuraCompra.setTitle("Busqueda Asistida");
        jDialogFActuraCompra.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("Buscar :");
        jDialogFActuraCompra.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jDialogFActuraCompra.getContentPane().add(txtBuscarFactCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 350, -1));

        jtablaFacturaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtablaFacturaCompra);

        jDialogFActuraCompra.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 460, 110));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion"));

        btnGrupoOpcion.add(jRInicio);
        jRInicio.setText("1) Coincida al Inicio");
        jRInicio.setToolTipText("Coincida al inicio");

        btnGrupoOpcion.add(jRFinal);
        jRFinal.setText("2)Coincida al Final");
        jRFinal.setToolTipText("Coincida al Final");

        btnGrupoOpcion.add(jrCualquier);
        jrCualquier.setSelected(true);
        jrCualquier.setText("3)Cualquier Caracter");
        jrCualquier.setToolTipText("Cualquier Caracter");

        btnGrupoOpcion.add(JRExacta);
        JRExacta.setText("5)Exacta");
        JRExacta.setToolTipText("Exacta");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jrCualquier)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JRExacta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jRInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrCualquier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRExacta)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jDialogFActuraCompra.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 140));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));

        btnGrupoBusqueda.add(jrCodigo2);
        jrCodigo2.setSelected(true);
        jrCodigo2.setText("Codigo");
        jrCodigo2.setToolTipText("Codigo");

        btnGrupoBusqueda.add(jrCliente);
        jrCliente.setText("Cliente");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jrCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jrCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrCodigo2)
                .addGap(11, 11, 11)
                .addComponent(jrCliente)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jDialogFActuraCompra.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, 100));

        btnAceptarFactCompra.setText("Aceptar");
        btnAceptarFactCompra.setToolTipText("Aceptar");
        jDialogFActuraCompra.getContentPane().add(btnAceptarFactCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 110, 30));

        btnCancelarFacturaCompra.setText("Cancelar");
        btnCancelarFacturaCompra.setToolTipText("Cancelar");
        jDialogFActuraCompra.getContentPane().add(btnCancelarFacturaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 110, 30));

        jDialogProveedor.setTitle("Busqueda Asistida");
        jDialogProveedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setText("Buscar :");
        jDialogProveedor.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 14, 60, -1));

        jtablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtablaProveedores);

        jDialogProveedor.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 50, 450, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion"));

        btnGrupoOpcioProv.add(jRInicioProv);
        jRInicioProv.setText("1) Inicio");
        jRInicioProv.setToolTipText("Coincida al inicio");

        btnGrupoOpcioProv.add(jRFinalProv);
        jRFinalProv.setText("2)Final");
        jRFinalProv.setToolTipText("Coincida al Final");

        btnGrupoOpcioProv.add(jrCualquierProv);
        jrCualquierProv.setSelected(true);
        jrCualquierProv.setText("3)Cualquier");
        jrCualquierProv.setToolTipText("Cualquier Caracter");

        btnGrupoOpcioProv.add(jRexactaProv);
        jRexactaProv.setText("4)exacta");
        jRexactaProv.setToolTipText("Exacta Caracter");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRFinalProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jrCualquierProv)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRInicioProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jRexactaProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jRInicioProv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFinalProv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrCualquierProv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRexactaProv)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jDialogProveedor.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 180, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));

        btnGrupoBusqudaProv.add(jrCodigo);
        jrCodigo.setSelected(true);
        jrCodigo.setText("Codigo");
        jrCodigo.setToolTipText("Codigo");

        btnGrupoBusqudaProv.add(jrDescripcion);
        jrDescripcion.setText("Descripcion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jrCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jrDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrCodigo)
                .addGap(11, 11, 11)
                .addComponent(jrDescripcion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogProveedor.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        btnAceptarDialoProv.setText("Aceptar");
        jDialogProveedor.getContentPane().add(btnAceptarDialoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 98, -1));

        btnCancelarProv.setText("Cancelar");
        btnCancelarProv.setToolTipText("Cancelar");
        jDialogProveedor.getContentPane().add(btnCancelarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 100, -1));

        jLabel34.setText("Total de Registros Encontrados");
        jDialogProveedor.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 161, -1));
        jDialogProveedor.getContentPane().add(txtBuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 350, -1));

        jDialogCondPago.setTitle("Busqueda Asistida");
        jDialogCondPago.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setText("Buscar :");
        jDialogCondPago.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        txtValorCondicionPago.setToolTipText("Valor");
        jDialogCondPago.getContentPane().add(txtValorCondicionPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 390, -1));

        jtablaCondicionPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtablaCondicionPago);

        jDialogCondPago.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 450, 120));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion"));

        btnGrupoOpcionCondPago.add(jRInicioCondPago);
        jRInicioCondPago.setText("1) Inicio");
        jRInicioCondPago.setToolTipText("Coincida al inicio");

        btnGrupoOpcionCondPago.add(jRFinalCondPago);
        jRFinalCondPago.setText("2)Final");
        jRFinalCondPago.setToolTipText("Coincida al Final");

        btnGrupoOpcionCondPago.add(jrCualquierCondPago);
        jrCualquierCondPago.setSelected(true);
        jrCualquierCondPago.setText("3)Cualquier");
        jrCualquierCondPago.setToolTipText("Cualquier Caracter");

        btnGrupoOpcionCondPago.add(jRexactaCondPago);
        jRexactaCondPago.setText("4)exacta");
        jRexactaCondPago.setToolTipText("Exacta Caracter");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRFinalCondPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jrCualquierCondPago)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jRInicioCondPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jRexactaCondPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jRInicioCondPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFinalCondPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrCualquierCondPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRexactaCondPago)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jDialogCondPago.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 130));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));

        jrCodigoCondPago.setSelected(true);
        jrCodigoCondPago.setText("Codigo");
        jrCodigoCondPago.setToolTipText("Codigo");

        jrDescripcionCondPago.setText("Descripcion");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrDescripcionCondPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jrCodigoCondPago, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jrCodigoCondPago)
                .addGap(18, 18, 18)
                .addComponent(jrDescripcionCondPago)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jDialogCondPago.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 100));

        btnAceptarCondicionPag.setText("Aceptar");
        jDialogCondPago.getContentPane().add(btnAceptarCondicionPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 98, -1));

        btnCancelarCondicionPag.setText("Cancelar");
        btnCancelarCondicionPag.setToolTipText("Cancelar");
        jDialogCondPago.getContentPane().add(btnCancelarCondicionPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, -1));

        jLabel36.setText("Total de Registros Encontrados");
        jDialogCondPago.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 180, -1));

        jDialogMoneda.setTitle("Busqueda Asistida");
        jDialogMoneda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setText("Buscar :");
        jDialogMoneda.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));
        jDialogMoneda.getContentPane().add(txtBuscarMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 380, -1));

        jtableMonedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jtableMonedas);

        jDialogMoneda.getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 120));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion"));

        jRInicioMoneda.setText("1) Inicio");
        jRInicioMoneda.setToolTipText("Coincida al inicio");

        jRFinalMoneda.setText("2)Final");
        jRFinalMoneda.setToolTipText("Coincida al Final");

        jrCualquierMoneda.setSelected(true);
        jrCualquierMoneda.setText("3)Cualquier");
        jrCualquierMoneda.setToolTipText("Cualquier Caracter");

        jRexactaMoneda.setText("4)exacta");
        jRexactaMoneda.setToolTipText("Exacta Caracter");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRFinalMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jrCualquierMoneda)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jRInicioMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jRexactaMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jRInicioMoneda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFinalMoneda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrCualquierMoneda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRexactaMoneda)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jDialogMoneda.getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 130));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));

        jrCodigoMoneda.setSelected(true);
        jrCodigoMoneda.setText("Codigo");
        jrCodigoMoneda.setToolTipText("Codigo");

        jrDescripcionMoneda.setText("Descripcion");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrDescripcionMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jrCodigoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jrCodigoMoneda)
                .addGap(18, 18, 18)
                .addComponent(jrDescripcionMoneda)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jDialogMoneda.getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 100));

        btnAceptarMonedas.setText("Aceptar");
        jDialogMoneda.getContentPane().add(btnAceptarMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 100, -1));

        btnCancelarmonedas.setText("Cancelar");
        jDialogMoneda.getContentPane().add(btnCancelarmonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, -1));

        jLabel38.setText("Total de Registros Encontrados");
        jDialogMoneda.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 180, -1));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar2.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnNuevo);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_icon.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_icon.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_icon.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnGuardar);

        btnactulizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        btnactulizar.setToolTipText("actualizar");
        btnactulizar.setEnabled(false);
        btnactulizar.setFocusable(false);
        btnactulizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnactulizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnactulizar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_1.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnEliminar);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_1.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnBuscar);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir_1.png"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnImprimir);

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar2.png"))); // NOI18N
        btnagregar.setFocusable(false);
        btnagregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnagregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnagregar);

        btnrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/restar.png"))); // NOI18N
        btnrestar.setFocusable(false);
        btnrestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrestar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnrestar);

        add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 40));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Numero :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Proveedor :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cod.Pago :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 20));
        jPanel1.add(txtCodPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));
        jPanel1.add(TxtDescripcionCodPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("N° Control :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 60, 20));
        jPanel1.add(txtNumFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 80, -1));
        jPanel1.add(txtNmControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 110, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripcion :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        jLabel6.setText("Fecha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 20));

        jLabel7.setText("Venc:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, 20));

        jLabel8.setText("Fecha Reg:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, 20));

        jLabel11.setText("Moneda.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 50, -1));
        jPanel1.add(txtCodMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 70, -1));
        jPanel1.add(TxtMoneda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 200, -1));

        jButton1.setText("Conversion");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 100, -1));
        jPanel1.add(txtTasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 100, -1));

        jTabbedPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablaFacturaCompraRenglon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablaFacturaCompraRenglon);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1010, 110));

        jTabbedPane2.addTab("Detalles", jPanel3);

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Desea Calcular el IGTF ?");
        jPanel20.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 20));

        jCheckBox1.setText("SI");
        jPanel20.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 40, -1));

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("3 %");
        jPanel20.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 20));

        txtMontoIGTF.setToolTipText("");
        jPanel20.add(txtMontoIGTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, -1));

        jTabbedPane2.addTab("IGTF", jPanel20);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1030, 160));

        jButton2.setText("Articulos");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jButton3.setText("Importar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 80, -1));

        jButton4.setText("Cobrar");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 70, -1));

        jButton5.setText("Costos");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 70, -1));

        jButton6.setText("Despachar");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, -1));

        jButton7.setText("Anular");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 70, -1));

        jLabel12.setText("%");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel13.setText("Monto");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel14.setText("Desc:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));
        jPanel1.add(txtDescuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 40, -1));
        jPanel1.add(txtMontoDescuentoGlobal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 120, -1));

        jLabel15.setText("Rec:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));
        jPanel1.add(txtRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 40, -1));

        txtMontoporc_recal.setToolTipText("");
        jPanel1.add(txtMontoporc_recal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 120, -1));

        jLabel16.setText("Sub-Total:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 60, 20));

        txtSubTotalBruto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubTotalBruto.setToolTipText("");
        jPanel1.add(txtSubTotalBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 90, -1));

        jLabel17.setText("I.V.A:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, -1, 20));

        txtImpuesto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtImpuesto.setToolTipText("");
        jPanel1.add(txtImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 90, -1));

        jLabel18.setText("Otros:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, 20));

        txtOtros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 90, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        txtTotalNeto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalNeto.setToolTipText("");
        jPanel1.add(txtTotalNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 90, -1));

        jLabel20.setText("Saldo:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 40, 20));
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, -1));

        jLabel21.setText("Total:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, 20));
        jPanel1.add(fechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 130, -1));
        jPanel1.add(fechaFacturaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 150, -1));
        jPanel1.add(fechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 130, -1));

        jLabel29.setText("Estatus:");
        jLabel29.setToolTipText("");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, 20));

        txtStatus.setToolTipText("");
        txtStatus.setEnabled(false);
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 110, -1));
        jPanel1.add(txtNumDocumentCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 270, -1));
        jPanel1.add(txtcdiProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, -1));
        jPanel1.add(txtDescripcionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 190, -1));
        jPanel1.add(txtDescripcionFactCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, -1));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("Monto en otra moneda :");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 180, -1));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("N° Factura :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 20));

        jLabelAnulado.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelAnulado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnulado.setText("ANULADO");
        jPanel1.add(jLabelAnulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 290, 40));

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Direccion de Entrega:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 60));
        jPanel2.add(TxtDireccionEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 490, 50));

        jLabel23.setText("Campo1");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel2.add(TxtCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 160, 30));

        jLabel24.setText("Campo2");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 60, -1));
        jPanel2.add(TxtCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 30));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Cuent In Egre :");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, -1));
        jPanel2.add(TxtCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 160, 30));

        jLabel26.setText("Campo4");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 50, 20));
        jPanel2.add(TxtCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 160, 30));

        jLabel27.setText("Campo5");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 50, -1));
        jPanel2.add(TxtCampo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 160, 30));

        jLabel28.setText("Campo6");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 60, -1));
        jPanel2.add(TxtCampo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 160, 30));
        jPanel2.add(txtCuentIngEgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 490, 30));

        jLabel41.setText("Campo3");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 70, -1));
        jPanel2.add(txtComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 490, 50));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Comentario :");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 60));

        jTabbedPane1.addTab("Adicionales", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1050, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton JRExacta;
    public javax.swing.JTextField TxtCampo1;
    public javax.swing.JTextField TxtCampo2;
    public javax.swing.JTextField TxtCampo3;
    public javax.swing.JTextField TxtCampo4;
    public javax.swing.JTextField TxtCampo5;
    public javax.swing.JTextField TxtCampo6;
    public javax.swing.JTextField TxtDescripcionCodPago;
    public javax.swing.JTextField TxtDireccionEntrega;
    public javax.swing.JTextField TxtMoneda2;
    public javax.swing.JButton btnAceptarCondicionPag;
    public javax.swing.JButton btnAceptarDialoProv;
    public javax.swing.JButton btnAceptarFactCompra;
    public javax.swing.JButton btnAceptarMonedas;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelarCondicionPag;
    public javax.swing.JButton btnCancelarFacturaCompra;
    public javax.swing.JButton btnCancelarProv;
    public javax.swing.JButton btnCancelarmonedas;
    public javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrupoBusqudaProv;
    private javax.swing.ButtonGroup btnGrupoBusqueda;
    private javax.swing.ButtonGroup btnGrupoOpcioProv;
    private javax.swing.ButtonGroup btnGrupoOpcion;
    private javax.swing.ButtonGroup btnGrupoOpcionCondPago;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnImprimir;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnactulizar;
    public javax.swing.JButton btnagregar;
    public javax.swing.JButton btnrestar;
    public com.toedter.calendar.JDateChooser fechaFacturaActual;
    public com.toedter.calendar.JDateChooser fechaRegistro;
    public com.toedter.calendar.JDateChooser fechaVencimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JDialog jDialogCondPago;
    public javax.swing.JDialog jDialogFActuraCompra;
    public javax.swing.JDialog jDialogMoneda;
    public javax.swing.JDialog jDialogProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelAnulado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JRadioButton jRFinal;
    public javax.swing.JRadioButton jRFinalCondPago;
    public javax.swing.JRadioButton jRFinalMoneda;
    public javax.swing.JRadioButton jRFinalProv;
    public javax.swing.JRadioButton jRInicio;
    public javax.swing.JRadioButton jRInicioCondPago;
    public javax.swing.JRadioButton jRInicioMoneda;
    public javax.swing.JRadioButton jRInicioProv;
    public javax.swing.JRadioButton jRexactaCondPago;
    public javax.swing.JRadioButton jRexactaMoneda;
    public javax.swing.JRadioButton jRexactaProv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTable jTablaFacturaCompraRenglon;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JRadioButton jrCliente;
    public javax.swing.JRadioButton jrCodigo;
    public javax.swing.JRadioButton jrCodigo2;
    public javax.swing.JRadioButton jrCodigoCondPago;
    public javax.swing.JRadioButton jrCodigoMoneda;
    public javax.swing.JRadioButton jrCualquier;
    public javax.swing.JRadioButton jrCualquierCondPago;
    public javax.swing.JRadioButton jrCualquierMoneda;
    public javax.swing.JRadioButton jrCualquierProv;
    public javax.swing.JRadioButton jrDescripcion;
    public javax.swing.JRadioButton jrDescripcionCondPago;
    public javax.swing.JRadioButton jrDescripcionMoneda;
    public javax.swing.JTable jtablaCondicionPago;
    public javax.swing.JTable jtablaFacturaCompra;
    public javax.swing.JTable jtablaProveedores;
    public javax.swing.JTable jtableMonedas;
    public javax.swing.JTextField txtBuscarFactCompra;
    public javax.swing.JTextField txtBuscarMoneda;
    public javax.swing.JTextField txtBuscarProveedor;
    public javax.swing.JTextField txtCodMoneda;
    public javax.swing.JTextField txtCodPago;
    public javax.swing.JTextField txtComentario;
    public javax.swing.JTextField txtCuentIngEgr;
    public javax.swing.JTextField txtDescripcionFactCompra;
    public javax.swing.JTextField txtDescripcionProveedor;
    public javax.swing.JTextField txtDescuesto;
    public javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtMontoDescuentoGlobal;
    public javax.swing.JTextField txtMontoIGTF;
    public javax.swing.JTextField txtMontoporc_recal;
    public javax.swing.JTextField txtNmControl;
    public javax.swing.JTextField txtNumDocumentCompra;
    public javax.swing.JTextField txtNumFactura;
    public javax.swing.JTextField txtOtros;
    public javax.swing.JTextField txtRec;
    public javax.swing.JTextField txtSaldo;
    public javax.swing.JTextField txtStatus;
    public javax.swing.JTextField txtSubTotalBruto;
    public javax.swing.JTextField txtTasa;
    public javax.swing.JTextField txtTotalNeto;
    public javax.swing.JTextField txtValorCondicionPago;
    public javax.swing.JTextField txtcdiProveedor;
    // End of variables declaration//GEN-END:variables
}
