/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author AranaV
 */
public class VistaNotadeEntrega extends javax.swing.JPanel {

    /**
     * Creates new form VistaNotadeEntrega
     */
    public VistaNotadeEntrega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtCodPago = new javax.swing.JTextField();
        TxtDescripcionCodPago = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodVendedor = new javax.swing.JTextField();
        TxtVendedor2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTransporte = new javax.swing.JTextField();
        TxtTransporte2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TxtMoneda = new javax.swing.JTextField();
        TxtMoneda2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTasa = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaFacturaVentaRenglon = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        txtMontoIGTF = new javax.swing.JTextField();
        btnFacturar = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtDescuesto = new javax.swing.JTextField();
        txtMontoDescuento = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtRec = new javax.swing.JTextField();
        TxtRec2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtSubTotalBruto = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtOtros = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTotalNeto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fechaRegistro = new com.toedter.calendar.JDateChooser();
        fechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        txtNumFacturaVenta = new javax.swing.JTextField();
        txtcdiCliente = new javax.swing.JTextField();
        txtDescripcionClientes = new javax.swing.JTextField();
        txtDescripcionFactVentas = new javax.swing.JTextField();
        txtNroControlFactVentura = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtCampo1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtCamppo3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtCampo2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtCampo4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtCampo5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtCampo6 = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        btnNuevo1 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        btnactulizar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        btnImprimir1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Numero :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cliente :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 50, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cod.Pago :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, 20));
        jPanel1.add(TxtCodPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, -1));
        jPanel1.add(TxtDescripcionCodPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Vendedor :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 20));
        jPanel1.add(txtCodVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 60, -1));
        jPanel1.add(TxtVendedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripcion :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 20));

        jLabel7.setText("Fecha :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 40, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Fecha Entrega:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 20, 100, 20));

        jLabel9.setText("N° Control:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 60, 20));

        jLabel10.setText("Transporte:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 20));
        jPanel1.add(txtTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 70, -1));
        jPanel1.add(TxtTransporte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 230, -1));

        jLabel26.setText("Moneda.");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 50, -1));
        jPanel1.add(TxtMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 70, -1));
        jPanel1.add(TxtMoneda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 200, -1));

        jButton1.setText("Conversion");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 100, -1));
        jPanel1.add(txtTasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 100, -1));

        jTabbedPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablaFacturaVentaRenglon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablaFacturaVentaRenglon);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1010, 110));

        jTabbedPane2.addTab("Detalles", jPanel3);

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Desea Calcular el IGTF ?");
        jPanel20.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 20));

        jCheckBox1.setText("SI");
        jPanel20.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 40, -1));

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("3 %");
        jPanel20.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 20));

        txtMontoIGTF.setToolTipText("");
        jPanel20.add(txtMontoIGTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, -1));

        jTabbedPane2.addTab("IGTF", jPanel20);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1030, 160));

        btnFacturar.setText("Facturar");
        jPanel1.add(btnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 80, -1));

        btnProcesar.setText("Procesar");
        jPanel1.add(btnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 90, -1));

        jButton4.setText("Cobrar");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 80, -1));

        jButton5.setText("Costos");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 80, -1));

        jButton6.setText("Despachar");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 90, -1));

        jLabel27.setText("%");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel28.setText("Monto");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel29.setText("Desc:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));
        jPanel1.add(txtDescuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 40, -1));
        jPanel1.add(txtMontoDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 120, -1));

        jLabel30.setText("Rec:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));
        jPanel1.add(txtRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 40, -1));

        TxtRec2.setToolTipText("");
        jPanel1.add(TxtRec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 120, -1));

        jLabel31.setText("Sub-Total:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 60, 20));

        txtSubTotalBruto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubTotalBruto.setToolTipText("");
        jPanel1.add(txtSubTotalBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 90, -1));

        jLabel32.setText("I.V.A:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, -1, 20));

        txtImpuesto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtImpuesto.setToolTipText("");
        jPanel1.add(txtImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 90, -1));

        jLabel18.setText("Otros:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, 20));

        txtOtros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 90, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        txtTotalNeto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalNeto.setToolTipText("");
        jPanel1.add(txtTotalNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 90, -1));

        jLabel20.setText("Saldo:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 40, 20));
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, -1));

        jLabel21.setText("Total:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, 20));
        jPanel1.add(fechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 130, -1));
        jPanel1.add(fechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 130, -1));

        jLabel33.setText("Estatus:");
        jLabel33.setToolTipText("");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, 20));

        txtStatus.setToolTipText("");
        txtStatus.setEnabled(false);
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 110, -1));
        jPanel1.add(txtNumFacturaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 270, -1));
        jPanel1.add(txtcdiCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 60, -1));
        jPanel1.add(txtDescripcionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, -1));
        jPanel1.add(txtDescripcionFactVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 270, -1));

        txtNroControlFactVentura.setToolTipText("");
        jPanel1.add(txtNroControlFactVentura, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 130, -1));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("Monto en otra moneda :");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 180, -1));

        jButton7.setText("Importar");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 90, -1));

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Direccion de Entrega:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 35, -1, -1));
        jPanel2.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 410, 90));

        jLabel12.setText("Campo1");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        jPanel2.add(TxtCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, 40));

        jLabel13.setText("Campo3");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));
        jPanel2.add(TxtCamppo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, 40));

        jLabel14.setText("Campo2");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jPanel2.add(TxtCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, 40));

        jLabel15.setText("Campo4");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 50, 20));
        jPanel2.add(TxtCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 120, 40));

        jLabel16.setText("Campo5");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 50, -1));
        jPanel2.add(TxtCampo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 120, 40));

        jLabel17.setText("Campo6");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 40, -1));
        jPanel2.add(TxtCampo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 120, 40));

        jTabbedPane1.addTab("Adicionales", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1040, 530));

        jToolBar2.setRollover(true);

        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo1.setToolTipText("Nuevo");
        btnNuevo1.setFocusable(false);
        btnNuevo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnNuevo1);

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_icon.png"))); // NOI18N
        btnGuardar1.setToolTipText("Guardar");
        btnGuardar1.setFocusable(false);
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnGuardar1);

        btnactulizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        btnactulizar.setToolTipText("actualizar");
        btnactulizar.setFocusable(false);
        btnactulizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnactulizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnactulizar);

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_1.png"))); // NOI18N
        btnEliminar1.setToolTipText("Eliminar");
        btnEliminar1.setFocusable(false);
        btnEliminar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnEliminar1);

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_1.png"))); // NOI18N
        btnBuscar1.setToolTipText("Buscar");
        btnBuscar1.setFocusable(false);
        btnBuscar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnBuscar1);

        btnImprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir_1.png"))); // NOI18N
        btnImprimir1.setToolTipText("Imprimir");
        btnImprimir1.setFocusable(false);
        btnImprimir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnImprimir1);

        add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField TxtCampo1;
    public javax.swing.JTextField TxtCampo2;
    public javax.swing.JTextField TxtCampo4;
    public javax.swing.JTextField TxtCampo5;
    public javax.swing.JTextField TxtCampo6;
    public javax.swing.JTextField TxtCamppo3;
    public javax.swing.JTextField TxtCodPago;
    public javax.swing.JTextField TxtDescripcionCodPago;
    public javax.swing.JTextField TxtDireccion;
    public javax.swing.JTextField TxtMoneda;
    public javax.swing.JTextField TxtMoneda2;
    public javax.swing.JTextField TxtRec2;
    public javax.swing.JTextField TxtTransporte2;
    public javax.swing.JTextField TxtVendedor2;
    public javax.swing.JButton btnBuscar1;
    public javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnFacturar;
    public javax.swing.JButton btnGuardar1;
    public javax.swing.JButton btnImprimir1;
    public javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnProcesar;
    public javax.swing.JButton btnactulizar;
    public com.toedter.calendar.JDateChooser fechaRegistro;
    public com.toedter.calendar.JDateChooser fechaVencimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTable jTablaFacturaVentaRenglon;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTextField txtCodVendedor;
    public javax.swing.JTextField txtDescripcionClientes;
    public javax.swing.JTextField txtDescripcionFactVentas;
    public javax.swing.JTextField txtDescuesto;
    public javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtMontoDescuento;
    public javax.swing.JTextField txtMontoIGTF;
    public javax.swing.JTextField txtNroControlFactVentura;
    public javax.swing.JTextField txtNumFacturaVenta;
    public javax.swing.JTextField txtOtros;
    public javax.swing.JTextField txtRec;
    public javax.swing.JTextField txtSaldo;
    public javax.swing.JTextField txtStatus;
    public javax.swing.JTextField txtSubTotalBruto;
    public javax.swing.JTextField txtTasa;
    public javax.swing.JTextField txtTotalNeto;
    public javax.swing.JTextField txtTransporte;
    public javax.swing.JTextField txtcdiCliente;
    // End of variables declaration//GEN-END:variables
}
