/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Beans.EmpresasBO;
import Controller.EmpresaController;
import Model.EmpresaModel;
import java.util.ArrayList;

/**
 *
 * @author Desarrollo
 */
public class VistaEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form VistaEmpresa
     */
    EmpresaController controller;
    EmpresaModel modelo;
    ArrayList<EmpresasBO> lista;
    public static String tempUsuario , tempEmpresa;
    
    
    public VistaEmpresa() {
        initComponents();
        controller = new EmpresaController(this); 
        modelo= new EmpresaModel();
        llenarlista();
        btnAceptar.addActionListener(controller);
        
    }

    
    public void llenarlista(){
       lista = new ArrayList<EmpresasBO>();
       lista = modelo.pObtenerMpEmpresa("" ,1);
        for (int i = 0; i < lista.size(); i++) {
            jComboEmpresas.addItem(lista.get(i).getDesc_empresa().toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbLEmpresas = new javax.swing.JLabel();
        jComboEmpresas = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbLEmpresas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbLEmpresas.setText("Empresas");
        LbLEmpresas.setToolTipText("");
        getContentPane().add(LbLEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 200, 30));

        getContentPane().add(jComboEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 240, -1));

        btnAceptar.setText("Aceptar");
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Empresa.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 100, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LbLEmpresas;
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JComboBox<String> jComboEmpresas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
