/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JpanelReport;

/**
 *
 * @author AranaV
 */
public class PanelReportProveerdoDatosBasicos extends javax.swing.JPanel {

    /**
     * Creates new form PanelReportProveerdoDatosBasicos
     */
    public PanelReportProveerdoDatosBasicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel32 = new javax.swing.JLabel();
        btnDesde = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtCodDesde = new javax.swing.JTextField();
        txtDescripcionDesde = new javax.swing.JTextField();
        txtCodHasta = new javax.swing.JTextField();
        txtDescripcionHasta = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Rangos :");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 48, -1));

        btnDesde.setText("Desde");
        add(btnDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, -1));

        jButton2.setText("Hasta");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 200, -1));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Codigo :");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, -1));
        add(txtCodDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, -1));

        txtDescripcionDesde.setText("jTextField1");
        add(txtDescripcionDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, -1));
        add(txtCodHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, -1));
        add(txtDescripcionHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 120, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesde;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JTextField txtCodDesde;
    private javax.swing.JTextField txtCodHasta;
    private javax.swing.JTextField txtDescripcionDesde;
    private javax.swing.JTextField txtDescripcionHasta;
    // End of variables declaration//GEN-END:variables
}
