/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaDialogos;

import Beans.ArticulosBO;
import Model.ArticuloModel;
import Model.ModelTablaArticulos;
import Vista.VistaAjustesES;
import Vista.Vistaprincipal;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.sql.Connection;
import Conection.Conexion;
import Vista.VistaCotizacionVenta;
import Vista.VistaFacturaCompras;

/**
 *
 * @author AranaV
 */
public class DialogoArticulos extends javax.swing.JDialog {

    /**
     * Creates new form DialogoArticulos
     */
    public VistaAjustesES ajustesES;
    public static int COLUMN_DESCRIPCION = 3, COLUMN_MODEL = 4, COLUMN_ALMACEN = 5, COLUMN_UNIDAD = 6, COLUMN_CANTIDAD = 7, COLUMN_COSTO_UNITARIO = 8, COLUMN_COSTO_TOTAL = 9;
    public Conexion conexion;
    public static Connection con;
    public VistaFacturaCompras facturaCompras;
    public VistaCotizacionVenta cotizacionVenta ;

    public DialogoArticulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = conexion.conexions();
        cargarDatosArtiuculos(
                Vistaprincipal.lblNombreEmpresa.getText(),
                "saArticulo",
                "",
                "",
                ""
        );
    }

    public void cargarDatosArtiuculos(
            String sDatabase_Name,
            String sTable_Name,
            String sField_Name,
            String sValor,
            String iOpcion
    ) {
        jtablaArticulos.setModel(new ModelTablaArticulos(new ArticuloModel().pObtenerListadoDatosArticulos(
                sDatabase_Name, //sDatabase_Name ,
                sField_Name,
                sValor,//valor
                "0",
                "1", "0", "0", "0", "0", "0", "0",
                /*
                 * Obligatorio tipo
                 */ "0",
                "V",
                "0", "", "0", "", "0", "", "0", "", "0", "", "0", "", "0", "", "0", "", iOpcion)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaArticulos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jRInicio = new javax.swing.JRadioButton();
        jRFinal = new javax.swing.JRadioButton();
        jrCualquier = new javax.swing.JRadioButton();
        jRexacta = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btngrupoBusquedArticulo = new javax.swing.JRadioButton();
        jrDescripcion = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBuscarArticulos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Asistida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtablaArticulos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion"));

        jRInicio.setText("1) Inicio");
        jRInicio.setToolTipText("Coincida al inicio");

        jRFinal.setText("2)Final");
        jRFinal.setToolTipText("Coincida al Final");

        jrCualquier.setSelected(true);
        jrCualquier.setText("3)Cualquier");
        jrCualquier.setToolTipText("Cualquier Caracter");

        jRexacta.setText("4)exacta");
        jRexacta.setToolTipText("Exacta Caracter");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jrCualquier)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jRexacta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jRInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrCualquier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRexacta)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 130));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));

        btngrupoBusquedArticulo.setSelected(true);
        btngrupoBusquedArticulo.setText("Codigo");
        btngrupoBusquedArticulo.setToolTipText("Codigo");

        jrDescripcion.setText("Descripcion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btngrupoBusquedArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btngrupoBusquedArticulo)
                .addGap(18, 18, 18)
                .addComponent(jrDescripcion)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 100));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 98, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, -1));

        jLabel15.setText("Total de Registros Encontrados");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 180, -1));

        jLabel14.setText("Buscar :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        txtBuscarArticulos.setToolTipText("");
        txtBuscarArticulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarArticulosKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        //Evento al Presionar el Boton Aceptar .

        ArrayList<ArticulosBO> lista = new ArticuloModel().pObtenerListadoDatosArticulos(
                Vistaprincipal.lblNombreEmpresa.getText(), //sDatabase_Name ,
                "",//sField_Name
                "",//valor
                "0",
                "1", "0", "0", "0", "0", "0", "0",
                /*
                 * Obligatorio tipo
                 */ "0",
                "V",
                "0", "", "0", "", "0", "", "0", "", "0", "", "0", "", "0", "", "0", "", "");
        int seleccionado = jtablaArticulos.getSelectedRow();
        String codArticulo = jtablaArticulos.getValueAt(seleccionado, 0).toString();

        System.out.println("Codi Articulo  " + codArticulo);
        double totalStock = 0, costoTotal = 0;

        if (seleccionado != -1) {

            //    System.out.println("cantidad de filas en la tabla" + ajustesES.jtableAjusteES.getRowCount());
            if (Utilitarios.Utilitario.MODULO_FACTURA_COMPRAS.equals("FACTURACOMPRA")) {
                System.out.println("ENTRADO AL METODO ");
                facturaCompras.jTablaFacturaCompraRenglon.setValueAt(codArticulo, facturaCompras.FILA_jtablaComprasreng, 1);
                facturaCompras.jTablaFacturaCompraRenglon.setValueAt(lista.get(seleccionado).getArt_des(), facturaCompras.FILA_jtablaComprasreng, 2);
                facturaCompras.jTablaFacturaCompraRenglon.setValueAt(Utilitarios.Utilitario.optenerCodUnidadArt(con, lista.get(seleccionado).getCo_art()), facturaCompras.FILA_jtablaComprasreng, 4);//UNIDAD
                System.out.println(" ARTICULO " + lista.get(seleccionado).getCo_art() + "  UNIDAD " + Utilitarios.Utilitario.optenerCodUnidadArt(con, lista.get(seleccionado).getCo_art()));

                dispose();
            }else if (Utilitarios.Utilitario.MODULO_COTIZACION_VENTAS.equals("COTIZACIONVENTA")){
                 System.out.println("ENTRADO condiciom COTIZACIONVENTA ");
                cotizacionVenta.jTablaCotizacionRenglon.setValueAt(codArticulo, cotizacionVenta.FILA_jtablaCotizacionReng, 1);
                cotizacionVenta.jTablaCotizacionRenglon.setValueAt(lista.get(seleccionado).getArt_des(), cotizacionVenta.FILA_jtablaCotizacionReng, 2);
                cotizacionVenta.jTablaCotizacionRenglon.setValueAt(Utilitarios.Utilitario.optenerCodUnidadArt(con, lista.get(seleccionado).getCo_art()), cotizacionVenta.FILA_jtablaCotizacionReng, 4);//UNIDAD
                System.out.println(" ARTICULO " + lista.get(seleccionado).getCo_art() + "  UNIDAD " + Utilitarios.Utilitario.optenerCodUnidadArt(con, lista.get(seleccionado).getCo_art()));

                dispose();
            }
            else {
                ajustesES.jtableAjusteES.setValueAt(lista.get(seleccionado).getCo_art(), ajustesES.FILA_jtableAjusteES, ajustesES.COLUMN_jtableAjusteES);
                ajustesES.jtableAjusteES.setValueAt(lista.get(seleccionado).getArt_des(), ajustesES.FILA_jtableAjusteES, COLUMN_DESCRIPCION);
                ajustesES.jtableAjusteES.setValueAt(lista.get(seleccionado).getModelo(), ajustesES.FILA_jtableAjusteES, COLUMN_MODEL);
                ajustesES.jtableAjusteES.setValueAt(Utilitarios.Utilitario.optenerCodUnidadArt(con, lista.get(seleccionado).getCo_art()), ajustesES.FILA_jtableAjusteES, 6);
                System.out.println(" ARTICULO " + lista.get(0).getCo_art() + "  UNIDAD " + Utilitarios.Utilitario.optenerCodUnidadArt(con, lista.get(seleccionado).getCo_art()));

                //realiza el ciclo para sumar la columna Cantidad y costo Total de la tabla Ajustes
                for (int i = 0; i < ajustesES.jtableAjusteES.getRowCount(); i++) {
                    totalStock += Double.parseDouble(ajustesES.jtableAjusteES.getValueAt(i, COLUMN_CANTIDAD).toString());
                    costoTotal += Double.parseDouble(ajustesES.jtableAjusteES.getValueAt(i, COLUMN_COSTO_TOTAL).toString());
                }
                ajustesES.txtTotalSto.setText(String.valueOf(totalStock));
                ajustesES.txtCostoTotal.setText(String.valueOf(costoTotal));
                dispose();
            }

            //ajustesES.jtableAjusteES.setValueAt(lista.get(seleccionado).getRelac_unidad(),ajustesES.FILA_jtableAjusteES,COLUMN_UNIDAD);
        } else {
            System.out.println("Debe seleccionar una fila en el articulo");
        }
        //agrega el resultado de la suma de las Columna Total Stock y Costo Total

    }//GEN-LAST:event_AceptarActionPerformed

    private void txtBuscarArticulosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarArticulosKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String Opcion = "0", sfieldName = "";

            if (jRInicio.isSelected()) {
                Opcion = "0";
            } else if (jRFinal.isSelected()) {
                Opcion = "1";
            } else if (jrCualquier.isSelected()) {
                Opcion = "2";
            } else if (jRexacta.isSelected()) {
                Opcion = "3";
            }
            sfieldName = (btngrupoBusquedArticulo.isSelected()) ? "co_art" : "art_des";
            cargarDatosArtiuculos(
                    Vistaprincipal.lblNombreEmpresa.getText(),
                    "saArticulo",
                    sfieldName,
                    txtBuscarArticulos.getText(),
                    Opcion
            );
        }
    }//GEN-LAST:event_txtBuscarArticulosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoArticulos dialog = new DialogoArticulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Aceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JRadioButton btngrupoBusquedArticulo;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JRadioButton jRFinal;
    public javax.swing.JRadioButton jRInicio;
    public javax.swing.JRadioButton jRexacta;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton jrCualquier;
    public javax.swing.JRadioButton jrDescripcion;
    public javax.swing.JTable jtablaArticulos;
    public javax.swing.JTextField txtBuscarArticulos;
    // End of variables declaration//GEN-END:variables
}
